/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginForm;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder; // For padding if needed

/**
 *
 * @author Admin
 */
public class oka extends javax.swing.JFrame {

    /**
     * Creates new form oka
     */
    public oka() {
        initComponents();
    }
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



/**
 *
 * @author ADMIN
 */
public class JLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form JLogin
     */
    public JLogin() {
        initComponents();
        // Set the background color for the frame's content pane
        getContentPane().setBackground(new Color(245, 245, 220)); // Light Beige/Cream - main window background
        setLocationRelativeTo(null); // Center the window on the screen
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField(); // This is Tài khoản (username) as per your current code mapping
        txtu = new javax.swing.JTextField(); // This is Mật khẩu (password) as per your current code mapping
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quán Cà Phê - Đăng Nhập"); // Set a themed title for the window

        // Styling for jPanel1 (the main login panel)
        jPanel1.setOpaque(true); // Make panel opaque so background color is visible
        jPanel1.setBackground(new java.awt.Color(250, 240, 230)); // Lighter beige/cream for panel background
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 78, 55), 3)); // Warm Brown border
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusCycleRoot(true);

        // Styling for jLabel1 (LOGIN title)
        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // Larger, bold Serif font for a classic look
        jLabel1.setForeground(new java.awt.Color(111, 78, 55)); // Warm Brown text color
        jLabel1.setText("LOGIN");

        // Styling for txtp (Tài khoản - username) text field
        txtp.setBackground(new java.awt.Color(255, 255, 255)); // White background for input area
        txtp.setForeground(new java.awt.Color(111, 78, 55)); // Warm Brown text color
        txtp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 78, 55), 1)); // Thin Warm Brown border
        txtp.setFont(new java.awt.Font("SansSerif", 0, 14)); // Clearer font

        // Styling for txtu (Mật khẩu - password) text field
        txtu.setBackground(new java.awt.Color(255, 255, 255)); // White background for input area
        txtu.setForeground(new java.awt.Color(111, 78, 55)); // Warm Brown text color
        txtu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 78, 55), 1)); // Thin Warm Brown border
        txtu.setFont(new java.awt.Font("SansSerif", 0, 14)); // Clearer font

        // Styling for jLabel2 ("Tài khoản:") label
        jLabel2.setText("Tài khoản:");
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // Slightly larger, clear font
        jLabel2.setForeground(new java.awt.Color(111, 78, 55)); // Warm Brown text

        // Styling for jLabel3 ("Mật khẩu:") label
        jLabel3.setText("Mật khẩu:");
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // Slightly larger, clear font
        jLabel3.setForeground(new java.awt.Color(111, 78, 55)); // Warm Brown text

        // Styling for the "Đăng nhập" button
        btnLog.setText("Đăng nhập");
        btnLog.setBackground(new java.awt.Color(139, 90, 43)); // Medium Brown button background
        btnLog.setForeground(new java.awt.Color(255, 255, 255)); // White text
        btnLog.setFont(new java.awt.Font("SansSerif", 1, 18)); // Bold, larger font
        btnLog.setBorder(new EmptyBorder(10, 25, 10, 25)); // Add padding to the button
        btnLog.setFocusPainted(false); // Remove focus border for cleaner look
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        // --- GroupLayout modifications for better spacing and alignment ---
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(215, 215, 215)) // Center "LOGIN" title
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)) // Adjusted width for consistent alignment
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE) // Slightly wider text fields
                    .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200) // Adjusted button position to be more centered
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE) // Fixed button width for consistency
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30) // More space above LOGIN title
                .addComponent(jLabel1)
                .addGap(80, 80, 80) // Space between title and first input field
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)) // Increased height for text field
                .addGap(40, 40, 40) // Space between input fields
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)) // Increased height for text field
                .addGap(70, 70, 70) // Space above button
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE) // Increased button height
                .addGap(60, 60, 60)) // More space below button
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE) // Add padding around the panel
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE)) // Add padding around the panel
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE) // Add padding around the panel
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE)) // Add padding around the panel
        );

        pack(); // Adjusts the window size to fit components
    }// </editor-fold>                        

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        // Use txtp for username and txtu for password, as per your current code's mapping
        String username = txtp.getText(); 
        String password = txtu.getText();
        
        if(username.equals("admin") && password.equals("admin123")){
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Assuming VAOQUANLY is another JFrame for manager
            VAOQUANLY vql = new VAOQUANLY(); 
            vql.setVisible(true);
            this.dispose(); // Close login window after successful login
        } else if(username.equals("nhanvien") && password.equals("nhanvienfree")){
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Assuming VAONHANVIEN is another JFrame for employee
            VAONHANVIEN vnv = new VAONHANVIEN(); 
            vnv.setVisible(true);
            this.dispose(); // Close login window after successful login
        } else {
            JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu!", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
        }
    }                                      




    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtp; // Tài khoản (username)
    private javax.swing.JTextField txtu; // Mật khẩu (password)
    // End of variables declaration                   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
