/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginForm;
import USERs.SP;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
/**
 *
 * @author ADMIN
 */
public class XemMELU extends javax.swing.JFrame {

    /**
     * Creates new form XemMELU
     */
    public XemMELU() {   
        initComponents();
         panelMenu.setLayout(new GridLayout(0, 4, 10, 10));
        panelMenu.setBackground(new Color(240, 248, 255)); 
        // Thêm tất cả các món với tên chuẩn và tệp ảnh khớp
        addMonMenu("Nâu đá", "28000", "60", "nau_da.jpg");
        addMonMenu("Sữa chua việt quất", "32000", "45", "sua_chua.jpg");
        addMonMenu("Cappuccino", "35000", "50", "Cappuccino.jpg");
        addMonMenu("Bạc xiu", "30000", "40", "bac-xiu.jpg");
        addMonMenu("Cà phê", "25000", "55", "ca_phe.jpg");
        addMonMenu("Matcha", "33000", "45", "matcha.jpg");
        addMonMenu("Cà phê trứng", "35000", "50", "ca-phe-trung.jpg");
        addMonMenu("Café espresso", "30000", "40", "cafe-espresso.jpg");
        addMonMenu("Sữa chua hoa quả", "32000", "45", "sua-chua-trai-cay.png");
        addMonMenu("Milo đá", "28000", "60", "milo_dam.jpg");
        addMonMenu("Mojito chanh dây", "35000", "50", "mojito_chanh_day.jpg");
        addMonMenu("Trà đào cam sả", "33000", "45", "tra-dao-cam-sa.jpg");

        panelMenu.revalidate();
        panelMenu.repaint();
        setSize(800, 700); 
        setLocationRelativeTo(null); 
    }

    private void addMonMenu(String tenMon, String gia, String soLuong, String pathAnh) {
        JPanel monPanel = new JPanel();
        monPanel.setLayout(new BorderLayout(10, 10));
        Border border = BorderFactory.createLineBorder(new Color(200, 200, 200), 1);
        monPanel.setBorder(BorderFactory.createCompoundBorder(border, BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        monPanel.setBackground(Color.WHITE);

        URL imgUrl = getClass().getClassLoader().getResource("images/" + pathAnh);
        if (imgUrl == null) {
            System.err.println("Không tìm thấy ảnh: " + pathAnh);
            return;
        }

        ImageIcon icon = new ImageIcon(imgUrl);
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        JLabel lblImage = new JLabel(new ImageIcon(img));
        monPanel.add(lblImage, BorderLayout.WEST);

        JPanel infoPanel = new JPanel(new GridLayout(3, 1));
        infoPanel.setBackground(Color.WHITE);
        infoPanel.add(new JLabel("Tên món: " + tenMon));
        infoPanel.add(new JLabel("Giá: " + gia + " VNĐ"));
        infoPanel.add(new JLabel("Số lượng: " + soLuong));
        monPanel.add(infoPanel, BorderLayout.CENTER);

        panelMenu.add(monPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("THANH TOÁN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 743, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn order sản phẩm?");
        int[] cotdachon = tblMenu.getSelectedRows();
        java.util.List<SP> selectedSPs = new java.util.ArrayList<>();

    for (int row : cotdachon) {
        String macp = (String) tblMenu.getValueAt(row, 0);
        String tencp = (String) tblMenu.getValueAt(row, 1);
        String uong = (String) tblMenu.getValueAt(row, 2);
        int gia = Integer.parseInt(tblMenu.getValueAt(row, 3).toString());
        String tinhtrang = (String) tblMenu.getValueAt(row, 4);
        int sl = Integer.parseInt(tblMenu.getValueAt(row, 5).toString());

        selectedSPs.add(new SP(macp, tencp, uong, gia, tinhtrang, sl));
    }
        if (result == JOptionPane.YES_OPTION) {
            ThanhToanHD tthd = new ThanhToanHD(selectedSPs);
            tthd.setVisible(true);
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "ok");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemMELU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemMELU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemMELU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemMELU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemMELU().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tblMenu;
    // End of variables declaration//GEN-END:variables
}
