/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginForm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class JLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form JLogin
     */
    public JLogin() {
        initComponents();
        initlayout();
    }
    
    public void initlayout(){
        this.setSize(700, 700);
        JButton btnlog = new JButton();
        btnlog.setSize(200, 50);
        btnlog.setText("Đăng nhập đi ơ");
        this.add(btnlog);
        btnlog.setLocation(175, 300);
        
        JLabel lblu = new JLabel();
        lblu.setSize(100,15);
        lblu.setText("Tên TK: ");
        this.add(lblu);
        lblu.setLocation(100, 157);
        JTextField txtu = new JTextField();
        txtu.setSize(250, 30);
        txtu.setText("");
        this.add(txtu);
        txtu.setLocation(150, 150);
        
        JLabel lblp = new JLabel();
        lblp.setSize(100, 15);
        lblp.setText("Mật khẩu: ");
        this.add(lblp);
        lblp.setLocation(100, 215);
        JTextField txtp = new JTextField();
        txtp.setSize(250, 30);
        txtp.setText("");
        this.add(txtp);
        txtp.setLocation(150, 208);
        
    btnlog.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String urename = txtu.getText();
            String pass = txtp.getText();
            if(urename.equals("admin") && pass.equals("admin123")){
                VAOQUANLY vql = new VAOQUANLY();
                vql.setVisible(true);
            }else if(urename.equals("nhanvien") && pass.equals("nhanvienfree")){
                
            }
        }
    });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
